### ISSUE TITLE
Extracting header from response and pasting it to another wsdl

### ISSUE THREAD

**Issue by Letme** [pysimplesoap/pysimplesoap#148]
I am writing a client for 2 wsdl's - one for Session (auth) and another for useful data. I am able to auth in this first session and debug trace clearly shows `sessionID`, but I am unable to extract `sessionID` via `response` variable (errors like NoneType, none, etc.). I did get some response variables via PolarionLogin.response , but there is no header in there. How can I extract and parse (probably xml) the header?

Code snippet
```python
PolarionLogin = SoapClient(wsdl='https://melexis.polarion.com/polarion/ws/services/SessionWebService?wsdl', trace = True)
response = PolarionLogin.logIn({'userName': self.username},{'password': self.password})
```
Debug printout (changed sessionID number in example):
```
DEBUG:pysimplesoap.client:b'<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-
instance"><soapenv:Header><ns1:sessionID soapenv:actor="http://schemas.xmlsoap.org/soap/actor/next"
 soapenv:mustUnderstand="0" xmlns:ns1="http://ws.polarion.com/session">-5643645324351234167</ns1:sessionID>
</soapenv:Header><soapenv:Body><logInResponse 
xmlns="http://ws.polarion.com/SessionWebService-impl"/></soapenv:Body></soapenv:Envelope>'
```

I am unable to find the old docs (or wiki), but it should be fairly common question. Thanks for help.

**Comment by osvalr** [comment]
what about using `PolarionLogin.xml_response` and parsing it with lxml? have you tried that?

**Comment by Letme** [comment]
I would thought there is a more library friendly way than parsing it as XML. I ended up using suds...
