### ISSUE TITLE
AttributeError: module httplib2 has no attribute SSLHandshakeError (python3)

### ISSUE THREAD

**Issue by lukio** [pysimplesoap/pysimplesoap#178]
Error at python3: AttributeError: module httplib2 has no attribute SSLHandshakeError

httplib2 at python3 does not support SSLHandshakeError any more.

So if there was an error at the connection, it does not throws which was the error, pysimplesoap throws an error regarding that httlib2 has no attribute SSLHandshakeError.

https://github.com/pysimplesoap/pysimplesoap/blob/stable_py3k/pysimplesoap/transport.py#L118

**Comment by FranTobar** [comment]
Pudiste resolver ese error? Porque me esta dando el mismo error

**Comment by crece365** [comment]
Alguna correción a este problema?

**Comment by lukio** [comment]
Hola @FranTobar @crece365, por el momento, el código de pysimplesoap no ha sido corregido y la versión con la que se ha implementado de httplib2 es la 0.9.2 (la cual todavía genera ese tipo de excepciones).

https://pypi.org/project/httplib2/0.9.2

**Comment by FranTobar** [comment]
Hola Luciano
Gracias por tu respuesta. Probe con varias versiones de pysimplesoap y
httplib2 y con ninguna puedo lograr conectarme a la AFIP y por ende no
puedo lograr facturar. Estoy Usando Odoo 13 en Ubuntu server 20.4.
Preguntando en algunos foros me recomendaron que instale Ubuntu 19 o
inferior. ¿Que me recomendas que haga para poder lograr una conexion con la
AFIP sin este error?
Gracias

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lukio** [comment]
Hola! No puedo hablar por odoo. Desde hace años venimos utilizando pysimplesoap y pyafipws con la localización de Tryton (https://github.com/tryton-ar)

No entiendo que tiene que ver cambiar de versión de ubuntu. Las versiones de pyafipws y pysimplesoap con los que trabajamos son las ramas de python3. 

Te dejo un enlace al respecto:
https://github.com/tryton-ar/account_invoice_ar/blob/master/setup.py#L68

Igualmente, si te esta dando ese error, es porque tenes un problema de conexión entre tu servidor y la afip. El problema acá es que pysimplesoap no lo esta manejando correctamente porque la versión de httplib2 con la que tenes instalado tu servidor no la conoce. Como te dije, la versión de httplib2 que necesitas es la 0.9.2

**Comment by vkmc** [comment]
Estoy teniendo el mismo problema y no es por la versión de httplib2 (tengo la recomendada, 0.9.2), sino porque en la implementación de Python 3 de httplib2 0.9.2 no se define esa excepción [0]

Creo que es en esta linea de pysimplesoap [1] se captura esa excepción, por ende, si estás usando un entorno con Python 3, por más que tengas httplib2 0.9.2, se va a seguir reproduciendo este bug.

Python 2 ya está deprecado y en las versiones más recientes ya no se están distribuyendo esos paquetes. Para Ubuntu 20.04, por ejemplo, la versión default de Python es py37.

Estoy viendo como resolver esto, si puedo arreglarlo les envio un pull request :)

[0] https://github.com/httplib2/httplib2/blob/0.9.2/python2/httplib2test.py#L530
[1] https://github.com/pysimplesoap/pysimplesoap/blob/stable_py3k/pysimplesoap/transport.py#L118

**Comment by cperezabo** [comment]
@vkmc hace unas semanas exactamente migré un modulo de facturación basado en **pyafipws** a **py3** y pasé por este mismo problema. En **py2** tenía andando todo con `httplib2=>0.9.2`

Ahora, en este repo no hay archivo de requirements, pero en **pyafipws** dentro de la rama `py3k` figura `httplib2>=0.12.0`, por lo que lo de la versión recomendada 0.9.2 no se si sigue siendo como decís. 🤔

Particularmente estoy usando `httplib2==0.18.1` y el error que se menciona acá lo corregí con un monkey patch que no pienso ni mencionar 🤣 para salir del paso y poder poner en producción porque había urgencia.

Para no dejarlo así me puse hoy justamente a trabajar en un PR sobre la rama `stable_py3k`, corregí de paso algunos tests rotos con errores de encoding derivados de los cambios en **py3** y quería saber si hiciste algunos avances con esto, como para no duplicar esfuerzos.

**Comment by cperezabo** [comment]
No armé un PR para no ensuciar este repositorio con basura que a lo mejor no sirve, pero en principio con este simple patch se resolvería: https://github.com/cperezabo/pysimplesoap/commit/cab60a8ad6d16953b281d3d685321e55f8d7ebc4

Comparando `testSslCertValidation`:
- Py2: https://github.com/httplib2/httplib2/blob/0.9.2/python2/httplib2test.py#L514
- Py3: https://github.com/httplib2/httplib2/blob/0.9.2/python3/httplib2test.py#L523

Encontramos que se modificó el set de excepciones y por ende fletaron a `httplib2.SSLHandshakeError` 🤣 dejando:

| Python2 | Python3 | Razón |
|---|---|---|
| ssl.SSLError | IOError | Archivo CA cert inexistente |
| httplib2.SSLHandshakeError | ssl.SSLError | Archivo CA cert invalido |

Así que cambiando `httplib2.SSLHandshakeError` por `IOError` se resuelve la cuestión.

**Comment by cperezabo** [comment]
@lukio estás seguro de que eliminando `SSLHandshakeError` asegura el correcto funcionamiento? Porque en base a lo que publicaste en https://github.com/lukio/pysimplesoap/commit/b3c1ce87703e80a27d9dd043cb06088874d65212 y a la tabla que yo presenté, solo estas cubriendo una de las dos situaciones de error que se dan.

**Comment by cperezabo** [comment]
... 🤨

@lukio ¿Por qué no integraste directamente mi rama? en lugar de:
1. mergear cambios incompletos en un commit aparte.
2. corregir esos cambios incompletos y (supongo que sucederá) volver a mergear.

**Comment by lukio** [comment]
> ... raised_eyebrow
> 
> @lukio ¿Por qué no integraste directamente mi rama? en lugar de:
> 
>     1. mergear cambios incompletos en un commit aparte.
> 
>     2. corregir esos cambios incompletos y (supongo que sucederá) volver a mergear.

Hola @cperezabo, la verdad es que no merge una rama tuya, porque no realizaste un pull request como ya habías comentado, así que en la apurada, arme un pull request y lo mergee. Espero que se entienda que no hay malas inteciones, sino ganas de avanzar. Pull request sobre este proyecto son más que bienvenidos.

Un abrazo y gracias por tus comentarios.

**Comment by cperezabo** [comment]
Hacer cosas a las apuradas no funciona nunca 🙂. 

Yo no hice pull request porque antes esperaba **debatir** sobre la solución propuesta. ¿Sino para que sirve este espacio? Si se consideraba adecuada la misma, creaba un PR.

No pasa nada, la próxima saldrá mejor! Lo bueno es que está fixeado! 🚀

**Comment by vkmc** [comment]
@cperezabo @lukio que bueno que ya resolvieron el problema, gracias por el fix!

**Comment by nicolaspeire** [comment]
Gracias @cperezabo por el fix, pude solucionar el problema de Facturación.

Tengo un error bastante similar pero al hacer la consulta de cuit (padrón a5).

File "/opt/odoo/extra-addons/ingadhoc-odoo-argentina/l10n_ar_account/models/res_partner.py", line 170, in get_data_from_padron_afip
    'Obtuvimos este error: %s' % (self.name, cuit, e.faultstring)))
AttributeError: 'SSLHandshakeError' object has no attribute 'faultstring'

Soy algo nuevo en github, perdón si el error corresponde al hilo.
