### ISSUE TITLE
Python 3 should be specified in setup.py

### ISSUE THREAD

**Issue by giampaolo** [pysimplesoap/pysimplesoap#53]
This is helpful for CLI tools like "caniusepython3". I erroneously thought this lib didn't have python 3 support because of that. 
Fixing this is easy. In setup.py:

    classifiers=[
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 3',
    ],

**Comment by reingart** [comment]
Thanks for reporting it, fixed in ad0fa12b5b6632050da39a43965e20eb53059698 (I'll add a long-description too)
