### ISSUE TITLE
Add some missing types to reverseTypeMap

### ISSUE THREAD

**Issue by ekzobrain** [pysimplesoap/pysimplesoap#72]
Some data types, defined by .NET soap generators are missing from typeMap. REVERSE_TYPE_MAP should be updated like this:

``` python
REVERSE_TYPE_MAP.update({
    'base64Binary': str,
    'unsignedByte': byte,
    'unsignedInt': int,
    'unsignedLong': long,
    'unsignedShort': short
})
```

@dotnetdan, this issue is originated from #42

**Comment by dotnetdan** [comment]
If possible, please provide a pull request for this with unit test coverage.
