### ISSUE TITLE
client crashes if wsdl does not define the Fault object

### ISSUE THREAD

**Issue by HuffAndPuff** [pysimplesoap/pysimplesoap#74]
[This line](https://github.com/pysimplesoap/pysimplesoap/blob/master/pysimplesoap/client.py#L265) assumes that the fault returned from the service is defined in the WSDL. This is not the case for the wsdl I'm working with and as far as I can see in the spec it's not mandatory either.

**Comment by dotnetdan** [comment]
I suppose thats true. According to the WSDL spec it must be defined, but
there will always be exceptions to the rule. Can you please submit a patch?
