### ISSUE TITLE
Sending a call and retrieving the xml output response.

### ISSUE THREAD

**Issue by encompass** [pysimplesoap/pysimplesoap#78]
Because of issues I would like to get the raw response from the call I make in pysimplesoap.  That way soap can make the calls and I can manually parse the xml when I need to.  Is there a parameter to make that happen or should I create the feature?

**Comment by encompass** [comment]
I tried making the pysimplesoap source return the xml object but that didn't work.  Still hacking at it and it would be great to have some help here.

**Comment by dotnetdan** [comment]
Hi, are you doing this for debug purposes or are you looking at this as a feature?

**Comment by encompass** [comment]
Feature.  That way if there is a bug in the application I can work around it.  I have it printing now, but haven't figured out how to return just the xml_response.

**Comment by dotnetdan** [comment]
I think it would be best to focus on fixing whatever issues are blocking you from using the library in the correct way.  As far as debugging needs, there are tracing options that we discussed in your other issue that allow you to view the raw xml data.
